export const APP_RESOURCE_LOADING = 'APP_RESOURCE_LOADING';
export const APP_RESOURCE_LOADING_COMPLETE = 'APP_RESOURCE_LOADING_COMPLETE';

export const APP_ERROR = 'CONVEY_APP_ERROR';
export const RESOLVE_APP_ERROR = 'RESOLVE_APP_ERROR';

export const ADD_USER = 'ADD_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const APP_MESSAGE = 'APP_MESSAGE';
export const RESOLVE_APP_MESSAGE = 'RESOLVE_APP_MESSAGE';
